### ISSUE TITLE
DSM 6 issue

### ISSUE THREAD

**Issue by Mootsj** [carljm/synology-mediamon#4]
Looks like the DSM 6 update has broken this, I've tried replaying steps 2-5 but it would appear there is no directory for /usr/syno/etc/rc.d/ anymore, tried installing in usr/local/etc/rc.d/ instead as i'd seen some posts suggesting that this is the place to install scripts so they're not affected by future upgrades but when trying to start the monitor i get the error below

Traceback (most recent call last):
  File "/root/mediamon.py", line 50, in <module>
    wm = pyinotify.WatchManager()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1776, in __init__
    self._inotify_wrapper = INotifyWrapper.create()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 128, in create
    if inotify.init():
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 212, in init
    libc_name = ctypes.util.find_library(try_libc_name)
  File "/usr/lib/python2.7/ctypes/util.py", line 247, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library c

**Comment by Tstassin** [comment]
Are you sure your Python and Inotify installation is ok ?

**Comment by Mootsj** [comment]
i think so, i've tried re-installing pip pyinotify with the python -m ensurepip pip install pyinotify commands which works as expected, i've even updated pip to the latest version just to make sure that it isn't something odd with an old version.

forgot to mention i've also updated mediation.py to show the directory as being local/etc rather than syno.

upgrading to DSM 6 removes the root user, so i've had to reinstall everything using an admin account with sudo su - to give me root access.

**Comment by Mootsj** [comment]
Looks like it's definitely an inotify issue, tried re-installing and it gave me a different error, manually re-installed and tried monitoring a directory and got the same error as above, i'll close this down and try find a resolution to the inotify problem, then remember not to upgrade again once it's working!

**Comment by lpinner** [comment]
I'm getting the same error with pyinotify, was working fine until upgrading to DSM6.0. DSM6.0 has broken a lot of stuff...

**Comment by Mootsj** [comment]
I couldn't get it working again so I've started using plex instead. Annoying as everything was set up perfectly before without having the need for another media server running on my NAS.

**Comment by carljm** [comment]
I'll take a look at this; if it's just a Python/pyinotify issue that should be solvable...

**Comment by carljm** [comment]
I think I've got this all fixed in 4bce9ce. Note that the big change is to use Python3 instead of Python 2 (the default Python module is Python 2). The other changes are just to put stuff in better places that won't be wiped on upgrade. The main `mediamon.py` Python script now goes in the admin user's homedir instead of in `/root/`, and the `S99mediamon.sh` now goes in `/usr/local/etc/rc.d/`, which is apparently the proper place to put user init scripts, and appears to also not be wiped on upgrade.

**Comment by Tstassin** [comment]
Great ! Thank you !

**Comment by lpinner** [comment]
Working for me, though I had to add the following to S99mediamon.sh

    PATH=$PATH:/usr/syno/bin
    export LANG='en_US.UTF-8'
    export LC_ALL='en_US.UTF-8'

Otherwise I would get the following errors:

      File "/volume1/@appstore/py3k/usr/local/lib/python3.5/subprocess.py", line 1544, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'synoindex'

and 

      File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/pyinotify.py", line 246, in _inotify_add_watch
        pathname = pathname.encode(sys.getfilesystemencoding())
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-23: ordinal not in range(128)

**Comment by carljm** [comment]
@lpinner that's odd, I'm not able to reproduce those failures, and I don't have those lines. `/usr/syno/bin` is already on my `PATH` (both for `admin` and `root` users; I think it's the latter that's relevant), and my `LANG` and `LC_ALL` are already `en_US.utf8`.

That said, I don't think it would hurt to enforce these things in the startup script, so if you supply a PR I'd merge it.
