### ISSUE TITLE
Self reindex share

### ISSUE THREAD

**Issue by Photographix** [carljm/synology-mediamon#8]
Hello,

is there a way to trigger self index (really real files) from volume/photo - aka real re-read? i have a cifs mount -bind folder connect to /volume1/photo and update the picture folder outside! from synology. the script does not add the new pictures to photostation.
tail -f /var/log/mediamon.log does not write "synoindex -a". ist clear after 2016-05-27T03:51:05.253766 - Starting

**Comment by carljm** [comment]
AFAIK that should trigger a synoindex -a. I'm afraid I can't really debug it for you remotely, but if you figure out a fix, feel free to submit it as a PR!

**Comment by Photographix** [comment]
Hello,

the script works locally perfectly. but the share is a remote share. I hoped that this can be indexed on another away. but the script only uses the system functions. the this is not able to remote mounted cifs shares. ticket can close.
