### ISSUE TITLE
Renamed folders not handled correctly

### ISSUE THREAD

**Issue by stigespen** [carljm/synology-mediamon#9]
I have the script running and working fine, watching /volume1/photo. Renamed folders are not handled correctly. 

Example
I type these commands:
admin@RackStationX:/volume1/photo$ mkdir FirstName
admin@RackStationX:/volume1/photo$ mv FirstName ChangedName
admin@RackStationX:/volume1/photo$ touch ChangedName/test.jpg

/var/log/mediamon.log show these corresponding entries:
2016-06-28T13:31:50.596390 - synoindex -D /volume1/photo/FirstName
2016-06-28T13:31:50.614578 - synoindex -A /volume1/photo/ChangedName
2016-06-28T13:31:57.253969 - synoindex -a /volume1/photo/FirstName/test.jpg

So I create a folder FirstName, rename it to ChangedName and put a file in it. The script sees the name change, but when I add a file to the folder it is still using the old directory name (FirstName) - and attempts to run synoindex on this non-existing path. 

Very annoying when using OS X Finder to add folder, as it creates all folders as "untitled folder" and then renames them.

**Comment by carljm** [comment]
Interesting. Not sure if this is a bug in the script or in the underlying watcher library. I probably won't have time to look into it any time soon, but if you get a chance to explore it and find a fix, I'd certainly take a pull request.

**Comment by carljm** [comment]
Fixed with merge of 10
